config/routes.rb
OmnioauthSample2::Application.routes.draw do
  get "home/index"
  root :to => 'home#index'
  match "/auth/google_login/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :access_token, :expires, :name, :provider, :refresh_token, :uid
  validates_uniqueness_of :uid, :scope => :provider
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth["provider"], :uid => auth["uid"]).first_or_initialize(
        :refresh_token => auth["credentials"]["refresh_token"],
        :access_token => auth["credentials"]["token"],
        :expires => auth["credentials"]["expires_at"],
        :name => auth["info"]["name"],
    )
    url = session[:return_to] || root_path
    session[:return_to] = nil
    url = root_path if url.eql?('/logout')

    if user.save
      session[:user_id] = user.id
      notice = "Signed in!"
      logger.debug "URL to redirect to: #{url}"
      redirect_to url, :notice => notice
    else
      raise "Failed to login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.haml
%h1 Home
- if flash[:notice]
  %h2 *** #{flash[:notice]} ***
- if current_user
  %p Welcome #{current_user.name}!
  %p
    = link_to "Sign Out", signout_path
- else
  %p
    = link_to "Sign in with Google google_login", "/auth/google_login"

    = link_to "Auth with Google google_auth", "/auth/google_auth"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OmnioauthSample2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>